{% set name = "cuda-nvdisasm" %}
{% set version = "12.9.19" %}
{% set cuda_version = "12.9" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/{{ platform }}/cuda_nvdisasm-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 50fa080f2aee29b390b6dbedcb6aac97442bd97449ebdaae456efc00151e0fe3  # [linux64]
  sha256: 42f56860ea7458fe98bc4a719f1619a559f213a4ba5ad9f3d3db8a2f7e23ab11  # [aarch64]
  sha256: ea737b7e9f6091b4119ee85f51496e7906b42e97912569331f035c977ec17979  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  script:
    - move bin\* %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf                                        # [linux]
  files:
    - test-rpath.sh                                   # [linux]
  commands:
    - test -f $PREFIX/bin/nvdisasm                    # [linux]
    - bash test-rpath.sh                              # [linux]
    - if not exist %LIBRARY_BIN%\nvdisasm.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvdisasm extracts information from standalone cubin files
  description: |
    nvdisasm extracts information from standalone cubin files and presents them in
    human readable format.
  doc_url: https://docs.nvidia.com/cuda/cuda-binary-utilities/

extra:
  recipe-maintainers:
    - conda-forge/cuda
